services:
  camera:
    build:
      context: .
      dockerfile: camera/Dockerfile
    ports:
      - "8001:8000"
    environment:
      CAMERA_SOURCE: 0
      DASHBOARD_URL: "http://192.168.1.50:8000"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - ./camera/weights:/app/weights
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dashboard/data:/app/data
    restart: unless-stopped